name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Simple CI
        uses: moghit-eou/DevSecOps-CI-pipelines/.github/actions/simple-ci
        with:
          first_step: 'Installing deps'
          second_step: 'Testing'
          third_step: 'Building'